name: Build

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.0.0'  # Укажите версию CMake

      - name: Install dependencies
        run: sudo apt-get install -y g++ make cmake

      - name: Build the project
        run: |
          mkdir .build
          cd .build
          cmake ../RC5
          cmake --build .
